
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.calculadorapedro.ws.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-09-01T17:00:37.128-03:00
 * Generated source version: 3.3.2
 *
 */

@javax.jws.WebService(
                      serviceName = "SomarWSService",
                      portName = "SomarWSPort",
                      targetNamespace = "http://ws.calculadorapedro.com.br/",
                      wsdlLocation = "file:/C:/projetosPessoais/jaxws/calculadoraws/tw-calculadoraPedro-ws/WebContent/wsdl/somarws.wsdl",
                      endpointInterface = "br.com.calculadorapedro.ws.client.SomarWSEndpoint")

public class SomarWSPortImpl implements SomarWSEndpoint {

    private static final Logger LOG = Logger.getLogger(SomarWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.calculadorapedro.ws.client.SomarWSEndpoint#somar(int arg0, int arg1)*
     */
    public int somar(int arg0, int arg1) {
        LOG.info("Executing operation somar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -509673757;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
