
package br.com.calculadorapedro.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-09-01T17:00:37.066-03:00
 * Generated source version: 3.3.2
 *
 */
public final class SomarWSEndpoint_SomarWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.calculadorapedro.com.br/", "SomarWSService");

    private SomarWSEndpoint_SomarWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SomarWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SomarWSService ss = new SomarWSService(wsdlURL, SERVICE_NAME);
        SomarWSEndpoint port = ss.getSomarWSPort();

        {
        System.out.println("Invoking somar...");
        int _somar_arg0 = -225234809;
        int _somar_arg1 = 1464068254;
        int _somar__return = port.somar(_somar_arg0, _somar_arg1);
        System.out.println("somar.result=" + _somar__return);


        }

        System.exit(0);
    }

}
