package br.com.calculadorapedro.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-09-01T17:00:37.142-03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ws.calculadorapedro.com.br/", name = "SomarWSEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface SomarWSEndpoint {

    @WebMethod(action = "urn:Somar")
    @RequestWrapper(localName = "somar", targetNamespace = "http://ws.calculadorapedro.com.br/", className = "br.com.calculadorapedro.ws.client.Somar")
    @ResponseWrapper(localName = "somarResponse", targetNamespace = "http://ws.calculadorapedro.com.br/", className = "br.com.calculadorapedro.ws.client.SomarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int somar(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
