
package br.com.calculadorapedro.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.2
 * Tue Aug 15 20:53:34 BRT 2023
 * Generated source version: 3.3.2
 */

@XmlRootElement(name = "somarResponse", namespace = "http://ws.calculadorapedro.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "somarResponse", namespace = "http://ws.calculadorapedro.com.br/")

public class SomarResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

